src/Entity/Core/Agenda.php
<?php

namespace App\Entity\Core;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Core\AgendaRepository")
 */
class Agenda
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", unique=true)
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\TimeRange", mappedBy="agenda", orphanRemoval=true)
     */
    private $timeRanges;

    /**
     * Agenda constructor.
     */
    public function __construct()
    {
        $this->timeRanges = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|TimeRange[]
     */
    public function getTimeRanges(): Collection
    {
        return $this->timeRanges;
    }

    public function addTimeRange(TimeRange $timeRange): self
    {
        if (!$this->timeRanges->contains($timeRange)) {
            $this->timeRanges[] = $timeRange;
            $timeRange->setAgenda($this);
        }

        return $this;
    }

    /**
     * @param TimeRange $timeRange
     * @return Agenda
     */
    public function removeTimeRange(TimeRange $timeRange): self
    {
        if ($this->timeRanges->contains($timeRange)) {
            $this->timeRanges->removeElement($timeRange);
            // set the owning side to null (unless already changed)
            if ($timeRange->getAgenda() === $this) {
                $timeRange->setAgenda(null);
            }
        }

        return $this;
    }
}

src/Entity/Core/ContactInstitution.php
<?php

namespace App\Entity\Core;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Core\ContactInstitutionRepository")
 */
class ContactInstitution
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * C'est l'intitulé custom pour un contact genre "Monsieur le Duc de la clinique"
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\PersonNatural", inversedBy="contactInstitutions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personNatural;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\PersonLegal", inversedBy="contactInstitutions")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $personLegal;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\JobName")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $function;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\ContactService", inversedBy="contactInstitutions")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $service;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * @param string $label
     * @return $this
     */
    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return PersonNatural|null
     */
    public function getPersonNatural(): ?PersonNatural
    {
        return $this->personNatural;
    }

    /**
     * @param PersonNatural|null $personNatural
     * @return $this
     */
    public function setPersonNatural(?PersonNatural $personNatural): self
    {
        $this->personNatural = $personNatural;

        return $this;
    }

    /**
     * @return PersonLegal|null
     */
    public function getPersonLegal(): ?PersonLegal
    {
        return $this->personLegal;
    }

    /**
     * @param PersonLegal|null $personLegal
     * @return $this
     */
    public function setPersonLegal(?PersonLegal $personLegal): self
    {
        $this->personLegal = $personLegal;

        return $this;
    }

    /**
     * @return JobName|null
     */
    public function getFunction(): ?JobName
    {
        return $this->function;
    }

    /**
     * @param JobName|null $function
     * @return $this
     */
    public function setFunction(?JobName $function): self
    {
        $this->function = $function;

        return $this;
    }

    /**
     * @return ContactService|null
     */
    public function getService(): ?ContactService
    {
        return $this->service;
    }

    /**
     * @param ContactService|null $service
     * @return $this
     */
    public function setService(?ContactService $service): self
    {
        $this->service = $service;

        return $this;
    }
}

src/Entity/Core/ContactService.php
<?php

namespace App\Entity\Core;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Core\ContactServiceRepository")
 */
class ContactService
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\ContactInstitution", mappedBy="service")
     */
    private $contactInstitutions;

    public function __construct()
    {
        $this->contactInstitutions = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * @param string $label
     * @return $this
     */
    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|ContactInstitution[]
     */
    public function getContactInstitutions(): Collection
    {
        return $this->contactInstitutions;
    }

    /**
     * @param ContactInstitution $contactInstitution
     * @return $this
     */
    public function addContactInstitution(ContactInstitution $contactInstitution): self
    {
        if (!$this->contactInstitutions->contains($contactInstitution)) {
            $this->contactInstitutions[] = $contactInstitution;
            $contactInstitution->setService($this);
        }

        return $this;
    }

    /**
     * @param ContactInstitution $contactInstitution
     * @return $this
     */
    public function removeContactInstitution(ContactInstitution $contactInstitution): self
    {
        if ($this->contactInstitutions->contains($contactInstitution)) {
            $this->contactInstitutions->removeElement($contactInstitution);
            // set the owning side to null (unless already changed)
            if ($contactInstitution->getService() === $this) {
                $contactInstitution->setService(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->label;
    }
}

src/Entity/Core/Person.php
<?php

namespace App\Entity\Core;

use App\Entity\Legacy\Legacy;
use App\Entity\Offer\Offer;
use App\Entity\Offer\Substitution;
use App\Entity\Offer\Wish;
use App\Traits\TranslatableTrait;
use App\Utils\DateTime;
use App\Utils\PHPHelper;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\OrderBy;
use Exception;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Core\PersonRepository")
 * @InheritanceType( "JOINED" )
 * @DiscriminatorColumn( name = "PERSON_TYPE", type = "string" )
 * @DiscriminatorMap( { "personLegal" = "PersonLegal",
 *                      "personNatural" = "PersonNatural" } )
 */
abstract class Person
{
    use TranslatableTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\Address",cascade={"persist"},inversedBy="person")
     */
    protected $addresses;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\Telephone",cascade={"persist"}, inversedBy="persons")
     */
    protected $telephones;

    /**
     * @ORM\ManyToMany(targetEntity="Service")
     */
    protected $services;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\Enrolment", mappedBy="personEnrolled")
     */
    protected $enrolments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\Discussion", mappedBy="person",cascade={"persist"}, orphanRemoval=true)
     * @OrderBy({"creationDate"="DESC"})
     */
    protected $discussions;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $personStatus;

    /**
     * Référence à l'entitée Legacy, pour l'historique
     * @ORM\OneToMany(targetEntity="App\Entity\Legacy\Legacy", mappedBy="person")
     */
    protected $legacies;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $creation_date;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\JobName", inversedBy="persons")
     */
    protected $jobNames;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Origin", inversedBy="persons")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $origin;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Core\Note", orphanRemoval=true, cascade={"persist", "remove"})
     */
    protected $additionalInformation;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Core\Agenda", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    protected $agenda;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Staff", inversedBy="personsCreated")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $creator;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\TimeRange", mappedBy="person")
     */
    protected $timeRanges;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\Mail",cascade={"persist"},inversedBy="persons")
     */
    protected $mails;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Offer\Substitution", mappedBy="person")
     */
    private $substitutions;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\JobName")
     */
    protected $mainJobName;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Offer\Offer", inversedBy="receivers")
     */
    private $offersSent;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $personToContact = [];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\Opinion", mappedBy="giver")
     */
    private $opinionsGiven;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Core\Opinion", mappedBy="receiver")
     */
    private $opinionsReceived;

    /**
     * Person constructor.
     */
    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->telephones = new ArrayCollection();
        $this->services = new ArrayCollection();
        $this->enrolments = new ArrayCollection();
        $this->discussions = new ArrayCollection();
        $this->legacies = new ArrayCollection();
        $this->creation_date = new DateTime();
        $this->timeRanges = new ArrayCollection();
        $this->substitutions = new ArrayCollection();
        $this->mails = new ArrayCollection();
        $this->jobNames = new ArrayCollection();
        $this->offersSent = new ArrayCollection();
        $this->opinionsGiven = new ArrayCollection();
        $this->opinionsReceived = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int|null
     */
    public function getPersonStatus(): ?int
    {
        return $this->personStatus;
    }

    /**
     * @param int|null $personStatus
     * @return Person
     */
    public function setPersonStatus(?int $personStatus): self
    {
        $this->personStatus = $personStatus;

        return $this;
    }

    /**
     * @return ArrayCollection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    /**
     * @param Address $address
     * @return Person
     */
    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->addPerson($this);
        }

        return $this;
    }

    /**
     * @param Address $address
     * @return Person
     */
    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            $address->removePerson($this);
        }

        return $this;
    }

    /**
     * @param Telephone $telephone
     * @return Person
     */
    public function addTelephone(Telephone $telephone): self
    {
        if (!$this->telephones->contains($telephone)) {
            $this->telephones[] = $telephone;
        }

        return $this;
    }

    /**
     * @param Telephone $telephone
     * @return Person
     */
    public function removeTelephone(Telephone $telephone): self
    {
        if ($this->telephones->contains($telephone)) {
            $this->telephones->removeElement($telephone);
        }

        return $this;
    }

    /**
     * @param int $type
     * @return ArrayCollection|Telephone[]
     */
    public function getTelephonesByType(int $type): Collection
    {
        $result = new ArrayCollection();
        foreach ($this->getTelephones() as $telephone) {
            if ($telephone->getPhoneType() === $type) {
                $result[] = $telephone;
            }
        }
        return $result;
    }

    /**
     * @return ArrayCollection|Telephone[]
     */
    public function getTelephones(): Collection
    {
        return $this->telephones;
    }

    /**
     * @return ArrayCollection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    /**
     * @param Service $service
     * @return Person
     */
    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
        }

        return $this;
    }

    /**
     * @param Service $service
     * @return Person
     */
    public function removeService(Service $service): self
    {
        if ($this->services->contains($service)) {
            $this->services->removeElement($service);
        }

        return $this;
    }

    /**
     * @return Collection|Enrolment[]
     */
    public function getEnrolments(): Collection
    {
        return $this->enrolments;
    }

    /**
     * @param Enrolment $enrolment
     * @return Person
     */
    public function addEnrolment(Enrolment $enrolment): self
    {
        if (!$this->enrolments->contains($enrolment)) {
            $this->enrolments[] = $enrolment;
            $enrolment->setPersonEnrolled($this);
        }

        return $this;
    }

    /**
     * @param Enrolment $enrolment
     * @return Person
     */
    public function removeEnrolment(Enrolment $enrolment): self
    {
        if ($this->enrolments->contains($enrolment)) {
            $this->enrolments->removeElement($enrolment);
            // set the owning side to null (unless already changed)
            if ($enrolment->getPersonEnrolled() === $this) {
                $enrolment->setPersonEnrolled(null);
            }
        }

        return $this;
    }

    /**
     * @Assert\Callback
     * @param ExecutionContextInterface $executionContext
     */
    public function validate(ExecutionContextInterface $executionContext)
    {
        if ($this->mails->count() > 0 && $this->getDefaultMail() === null) {
            $executionContext->buildViolation('Une adresse mail par défault est obligatoire')
                ->atPath("mails")
                ->addViolation();
        }
    }

    /**
     * @return Mail|null
     */
    public function getDefaultMail(): ?Mail
    {
        /**
         * @var Mail $mail
         */
        foreach ($this->mails as $mail) {
            if ($mail->getIsDefault()) {
                return $mail;
            }
        }
        return null;
    }

    /**
     * @return Collection|Discussion[]
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    /**
     * @param Discussion $discussion
     * @return Person
     */
    public function addDiscussion(Discussion $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {

templates/Core/ToolBox/toolBox.html.twig
{% block stylesheets %}
    {{ encore_entry_link_tags('cfml/toolbox') }}
{% endblock %}

{% block body %}
    <div class="toolbox {% if is_granted("ROLE_CFML" , app.user ) %} toolbox-icon {% endif %}">
        <ul class="m-0 p-0">
            <li>
                <a>
                    <i class="fas fa-comment-dots tool-box-links"
                       title='Nouvel échange'
                       onclick='popupOnHtmlResponse(this,"{{ url("core_discussion_new",{"id":personNatural.id}) }}")'></i>
                </a>
            </li>
            {% if personNatural.mainJobName.personAccesses[0] is defined and (is_granted(constant('DEPOSIT_LIBERAL_ANNOUNCE',personNatural.mainJobName.personAccesses[0]),personNatural) or
                is_granted(constant('DEPOSIT_TO_CESSION',personNatural.mainJobName.personAccesses[0]),personNatural)) and is_granted("ROLE_CFML" , app.user ) == false %}
                <li class="p-1">
                    <hr class="one-hr">
                    <a>
                        <i class="fas fa-user-md tool-box-links"
                           title="Création d'une offre"
                           onclick='popupOnHtmlResponse(this,"{{ url("offer_preselect_canvas",{'id':personNatural.id}) }}")'></i>
                    </a>
                </li>
            {% else %}
                {% if is_granted("ROLE_CFML" , app.user ) == false %}
                    <li class="p-1">
                        <hr class="one-hr">
                        <a href="{{ url('core_person_natural_add_offer', {'id':personNatural.id}) }}">
                            <i class="fas fa-user-md tool-box-links" title="Rechercher une offre"> </i>
                        </a>
                    </li>
                {% endif %}
            {% endif %}

            {% if personNatural.mainJobName.personAccesses[0] is defined and is_granted(constant('CANDIDATE_TO_LIBERAL_ANNOUNCE',personNatural.mainJobName.personAccesses[0]),personNatural)
                and  is_granted("ROLE_CFML" , app.user ) == false %}
                <li class="p-1">
                    <hr class="one-hr">
                    <a>
                        <i id="btn-send-one-offer"
                           class="fas fa-share-square tool-box-links"
                           title="Transmettre une offre"
                           data-person-id="{{ personNatural.id }}"> </i>{# la gestion de l'envoi de l'offre se fait dans mastchingSubstitute.js #}
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('offer_wish_new',{'personId':personNatural.id}) }}">
                        <i class="fas fa-cloud-upload-alt tool-box-links" title="Créer un souhait"></i>
                    </a>
                </li>
            {% endif %}
            <li class="p-1">
                <hr class="one-hr">
                <a>
                    <i class="fas fa-user-clock tool-box-links"
                       title='Définir un rappel pour le client n°{{ personNatural.id }}'
                       onclick='popupOnHtmlResponse(this,"{{ url("define_alarm_recall",{"id":personNatural.id,"agendaId":app.user.agenda.id}) }}")'>
                    </i>
                </a>
            </li>
            <li class="p-1">
                <hr class="one-hr">
                <a>
                    <i class="fas fa-paper-plane tool-box-links"
                       title="Notifier un membre du staff"
                       onclick='popupOnHtmlResponse(this,"{{ url('notification_new',{ 'id':personNatural.id }) }}")'>
                    </i>
                </a>
            </li>
            {% if personNatural.defaultMail %}
                <li class="p-1" data-controller="/core/person/natural/mail/exchange">
                    <hr class="one-hr">
                    <a href="{{ url('person_natural_mail_exchange', {'id':personNatural.id}) }}">
                        <i class="fas fa-envelope tool-box-links" title="Echanges de Mails"> </i>
                    </a>
                </li>
            {% endif %}
            {% if is_granted("ROLE_CFML" , app.user ) %}
                <li class="p-1">
                    <hr class="one-hr">
                    <div id="toolbox-person-infos" class="fixed-plugin toolboxCFML">
                        <div class="dropdown show-dropdown">
                            <a href="#" data-toggle="dropdown">
                                <i class="fas fa-copy" title="Info URSSAF"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header-title">
                                    <a id="dropdown-link-person"
                                       href="{{ path('core_person_natural_show' , {id : personNatural.id}) }}">
                                        {{ personNatural.name }} </a>
                                </li>
                                <li class="adjustments-line">
                                    <div class="customer-infos-title"><strong>URSSAF PAM</strong></div>
                                    <div>0806804209
                                    </div>
                                </li>
                                <li class="adjustments-line">
                                    <div class="customer-infos-title"><strong>URSSAF TI</strong></div>
                                    <div>3957
                                    </div>
                                </li>
                                <li class="adjustments-line">
                                    <div class="customer-infos-title"><strong> CARMF standard</strong></div>
                                    <div>0140683200
                                    </div>
                                </li>
                                <li class="adjustments-line">
                                    <div class="customer-infos-title"><strong><span
                                                    class="font-italic">CPAM </span></strong>
                                    </div>
                                    <div>3646
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_profil',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-single-02" title="PROFIL"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_data_tax',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-bank" title="Données Fiscales"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_urssaf',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-paper" title="Urssaf"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_estimate_contribution',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-alert-circle-exc"
                           title="Estimation URSSAF / CARMF"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_carmf',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-user-run" title="CARMF"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_membership_situation',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-single-copy-04" title="Situation adhésion"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_charge_social',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-badge"
                           title="Charges sociales - New charges sociales "></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_curps',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-components" title="CURPS"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_disease',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-sound-wave" title="Maladie"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_management_carmf',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links fa-folder-open"
                           title="CARMF gestion"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_bill',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-wallet-43" title="Facture"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_social_statement',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-book-bookmark" title="Déclarations Sociales"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_payement_urssaf',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-money-coins" title="Urssaf Règlement"></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a href="{{ url('cfml_verification_file',{"id":personNatural.id}) }}">
                        <i class="fas tool-box-links tim-icons icon-bag-16" title="Dossier de vérif."></i>
                    </a>
                </li>
                <li class="p-1">
                    <hr class="one-hr">
                    <a id="open-modal-gt" href="#" data-toggle="modal" data-target="#openModalGT">
                        <i class="fas tool-box-links tim-icons icon-chart-bar-32" title="Option GT"></i>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>

    {% if is_granted("ROLE_CFML" , app.user ) %}
        {# modal pour l'icon de CFML option GT (icon de fin ) #}
        <div class="modal fade" id="openModalGT" tabindex="-1" role="dialog" aria-labelledby="openModalGT"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Changement de statut GT</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Votre nouveau status à l'instant t</p>

                        <select class="form-control">
                            <option selected value="a">Ne dispose plus de GT</option>
                            <option value="b">Ne souhaite plus nous donner ses accès</option>
                        </select>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="button" class="btn btn-primary">Envoyer</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}